services:
  - type: web
    name: macro-dashboard
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run binance_widgets_tradingview.py --server.port $PORT --server.address 0.0.0.0
    autoDeploy: true
    envVars:
      - key: APP_USERNAME
        sync: false
      - key: APP_PASSWORD
        sync: false

